import 'normalize.css/normalize.css';
import './globals.scss'
import type { AppProps } from 'next/app';
import { Montserrat } from 'next/font/google'
import localfont from 'next/font/local';

const montserrat = Montserrat({ 
  weight: '400',
  subsets: ['latin'] 
})

const opensans = localfont({
  src: [
  { 
    path: '../../public/fonts/OpenSans-Regular.woff2',
    weight: '400',
    style: 'normal'
  }
  ]
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ Component, pageProps }: AppProps) {
  return (
    <>
      <style jsx global>{`
        html {
          font-family: ${montserrat.style.fontFamily}, ${opensans.style.fontFamily};
        }
      `}</style>
      <Component {...pageProps} />
    </>
  );
}
